# Site settings
title: Karthikkeyan Bala Sundaram
email: karthikkeyan.balan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My protfolio
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: iamkarthikkeyan
github_username: karthikkeyan

# Build settings
markdown: kramdown